# Generated by Django 6.0 on 2026-01-01 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('Provider Admin', 'Provider Admin'), ('Supplier Representative', 'Supplier Representative'), ('Contract Coordinator', 'Contract Coordinator'), ('Specialist', 'Specialist')], max_length=30)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateField()),
                ('photo', models.URLField(blank=True, null=True)),
                ('material_number', models.CharField(blank=True, max_length=50, null=True)),
                ('experience_level', models.CharField(blank=True, choices=[('Junior', 'Junior'), ('Mid', 'Mid'), ('Senior', 'Senior'), ('Expert', 'Expert')], max_length=10, null=True)),
                ('technology_level', models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=15, null=True)),
                ('performance_grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('average_daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('skills', models.JSONField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, choices=[('Available', 'Available'), ('Partially Booked', 'Partially Booked'), ('Fully Booked', 'Fully Booked')], max_length=20, null=True)),
                ('service_requests_completed', models.IntegerField(blank=True, null=True)),
                ('service_orders_active', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='providers.provider')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
