# Generated by Django 6.0 on 2025-12-23 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="provideruser",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="providers.provider",
            ),
        ),
        migrations.AddField(
            model_name="provideruser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddConstraint(
            model_name="roledefinition",
            constraint=models.UniqueConstraint(
                fields=("name", "domain", "group_name"),
                name="uniq_roledef_name_domain_group",
            ),
        ),
        migrations.AddField(
            model_name="userroleassignment",
            name="role_definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="accounts.roledefinition",
            ),
        ),
        migrations.AddField(
            model_name="userroleassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userroleassignment",
            index=models.Index(fields=["user"], name="accounts_us_user_id_25d3e4_idx"),
        ),
        migrations.AddIndex(
            model_name="userroleassignment",
            index=models.Index(
                fields=["role_definition"], name="accounts_us_role_de_e89845_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userroleassignment",
            index=models.Index(
                fields=["user", "role_definition", "status"],
                name="accounts_us_user_id_1f2512_idx",
            ),
        ),
    ]
