# Generated by Django 6.0 on 2025-12-23 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleRatePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("JUNIOR", "Junior"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("SENIOR", "Senior"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "technology_level",
                    models.CharField(
                        choices=[
                            ("COMMON", "Common"),
                            ("UNCOMMON", "Uncommon"),
                            ("RARE", "Rare"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "max_daily_rate_eur",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rate_policies",
                        to="accounts.roledefinition",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "role_definition",
                            "experience_level",
                            "technology_level",
                        ),
                        name="uniq_rate_policy_matrix",
                    )
                ],
            },
        ),
    ]
