"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.
API-only backend (frontend runs as a separate service).
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# ------------------------------------------------------------
# Base
# ------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-change-me-in-production",
)

DEBUG = os.getenv("DEBUG", "False") == "True"

# Comma-separated list in .env: ALLOWED_HOSTS=api.example.com,localhost,127.0.0.1
_allowed_hosts_env = os.getenv("ALLOWED_HOSTS", "*")
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(",") if h.strip()]

# ------------------------------------------------------------
# Applications
# ------------------------------------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",

    # Local apps
    "providers",
    "accounts",
    "procurement",
    "activitylog",
    "contracts",
]

# ------------------------------------------------------------
# Middleware
# ------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

# ------------------------------------------------------------
# Templates
# (Admin needs templates; API-only doesn't need extra template dirs)
# ------------------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# ------------------------------------------------------------
# Database
# ------------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.getenv("DB_NAME", "providers_db"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", "root"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}
print("Database settings:", DATABASES["default"])
# ------------------------------------------------------------
# Auth
# ------------------------------------------------------------
AUTH_USER_MODEL = "accounts.User"
AUTH_PASSWORD_VALIDATORS = []

# ------------------------------------------------------------
# Internationalization
# ------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Europe/Berlin"
USE_I18N = True
USE_TZ = True

# ------------------------------------------------------------
# Static files
# (Kept minimal for Django admin static; NOT serving frontend build)
# ------------------------------------------------------------
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# ------------------------------------------------------------
# DRF / JWT
# ------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

# ------------------------------------------------------------
# CORS (frontend is a different service)
# ------------------------------------------------------------
# Prefer explicit origins in production.
# .env example:
# CORS_ALLOWED_ORIGINS=http://localhost:5173,https://frontend.example.com
cors_allowed_origins_env = os.getenv("CORS_ALLOWED_ORIGINS", "")

if cors_allowed_origins_env.strip():
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [o.strip() for o in cors_allowed_origins_env.split(",") if o.strip()]
else:
    # Development convenience fallback (set to False in production)
    CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "True") == "True"

# If you use cookies/sessions across domains, enable the below and configure CSRF_TRUSTED_ORIGINS.
# For JWT in Authorization header, you typically do NOT need credentials.
CORS_ALLOW_CREDENTIALS = os.getenv("CORS_ALLOW_CREDENTIALS", "False") == "True"

# If CORS_ALLOW_CREDENTIALS=True and you use cookies, configure:
# CSRF_TRUSTED_ORIGINS=http://localhost:5173,https://frontend.example.com
csrf_trusted_origins_env = os.getenv("CSRF_TRUSTED_ORIGINS", "")
if csrf_trusted_origins_env.strip():
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in csrf_trusted_origins_env.split(",") if o.strip()]

# ------------------------------------------------------------
# Security (basic production hardening toggles)
# ------------------------------------------------------------
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

# ------------------------------------------------------------
# Default primary key field type
# ------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ------------------------------------------------------------
# --- Group 3 Integration (Service Management System) ---
# ------------------------------------------------------------
GROUP3_BIDS_URL = os.getenv(
    "GROUP3_BIDS_URL",
    "https://servicemanagementsystem-1-2s7d.onrender.com/api/public/bids",
)

GROUP3_EXTENSION_URL = os.getenv(
    "GROUP3_EXTENSION_URL",
    "https://servicemanagementsystem-1-2s7d.onrender.com/api/public/order-changes/extension",
)

GROUP3_SUBSTITUTION_URL = os.getenv(
    "GROUP3_SUBSTITUTION_URL",
    "https://servicemanagementsystem-1-2s7d.onrender.com/api/public/order-changes/substitution",
)

GROUP3_REQUESTS_URL = os.getenv(
    "GROUP3_REQUESTS_URL",
    "https://servicemanagementsystem-1-2s7d.onrender.com/api/requests",
)
GROUP3_CONNECTION_API_KEY = os.getenv("GROUP3_CONNECTION_API_KEY", "uni-project-2026-secret")
GROUP3_API_KEY_HEADER = os.getenv("GROUP3_API_KEY_HEADER", "ServiceRequestbids3a")

GROUP3_EXTENSION_DECISION_URL = os.getenv("GROUP3_EXTENSION_DECISION_URL", "")
GROUP3_SUBSTITUTION_DECISION_URL = os.getenv("GROUP3_SUBSTITUTION_DECISION_URL", "")

# ------------------------------------------------------------
# --- Group 2 Integration (Contracts) ---
# ------------------------------------------------------------
# Group2 - Contract Management (public API)
GROUP2_CONTRACTS_URL = "http://127.0.0.1:8001/api/public/contracts"

# Group2 offers endpoint template
GROUP2_CONTRACT_OFFER_URL_TEMPLATE = "http://127.0.0.1:8001/api/public/contracts/{contract_id}/offers"

# Existing (you already use something like this in Group2ApiKeyAuthentication)
GROUP2_API_KEY = "uni-project-2026-secret"

# ------------------------------------------------------------
# Logging
# ------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "root": {"handlers": ["console"], "level": os.getenv("LOG_LEVEL", "INFO")},
}
