"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.
"""
import os
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

SECRET_KEY = 'django-insecure-y=x5in!2(896cny5=sv&2mzyo_2@#rbaiei57p84ct(o1vbtma'
DEBUG = os.getenv("DEBUG", "False") == "True"
ALLOWED_HOSTS = ["*"]

# --- Group 3 Integration (Service Management System) ---
GROUP3_BIDS_URL = os.getenv(
    "GROUP3_BIDS_URL",
    "https://servicemanagementsystem-1-2s7d.onrender.com/api/public/bids",
)

GROUP3_EXTENSION_URL = os.getenv(
    "GROUP3_EXTENSION_URL",
    "https://servicemanagementsystem-1-2s7d.onrender.com/api/public/order-changes/extension",
)

GROUP3_SUBSTITUTION_URL = os.getenv(
    "GROUP3_SUBSTITUTION_URL",
    "https://servicemanagementsystem-1-2s7d.onrender.com/api/public/order-changes/substitution",
)

# API key shared with Group 3 (do NOT commit real value in public repos)
GROUP3_CONNECTION_API_KEY = os.getenv("GROUP3_CONNECTION_API_KEY", "uni-project-2026-secret")

# Group 3 expects this header name (case-insensitive in HTTP, but Django META uses upper)
GROUP3_API_KEY_HEADER = os.getenv("GROUP3_API_KEY_HEADER", "ServiceRequestbids3a")

GROUP3_EXTENSION_DECISION_URL = os.getenv("GROUP3_EXTENSION_DECISION_URL", "")
GROUP3_SUBSTITUTION_DECISION_URL = os.getenv("GROUP3_SUBSTITUTION_DECISION_URL", "")


GROUP2_API_KEY = os.getenv("GROUP2_API_KEY", "")
GROUP2_CONTRACTS_URL = os.getenv(
    "GROUP2_CONTRACTS_URL",
    "https://contractmanagement.example/api/contracts",  # placeholder default
)

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",

    "providers",
    "accounts",
    "procurement",
    "activitylog",
    "contracts",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"
    }
}


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "providers_db"),
        "USER": os.getenv("DB_USER" , "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", "root"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),}
}

print("Database settings:", DATABASES)

AUTH_PASSWORD_VALIDATORS = []

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Europe/Berlin'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.User"

CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}