# Generated by Django 6.0 on 2026-01-09 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('Service', 'Service'), ('License', 'License'), ('Hardware', 'Hardware')], default='Service', max_length=30)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('In Negotiation', 'In Negotiation'), ('Awarded', 'Awarded'), ('Active', 'Active'), ('Expired', 'Expired')], default='Draft', max_length=30)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('scope_of_work', models.TextField(blank=True, default='')),
                ('terms_and_conditions', models.TextField(blank=True, default='')),
                ('functional_weight', models.PositiveIntegerField(default=50)),
                ('commercial_weight', models.PositiveIntegerField(default=50)),
                ('allowed_request_configs', models.JSONField(blank=True, default=dict)),
                ('awarded_provider_id', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Countered', 'Countered'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Submitted', max_length=20)),
                ('proposed_daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('proposed_terms', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_offers_created', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_offers', to='providers.provider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
