# Generated by Django 6.0 on 2026-01-09 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='awarded_provider_id',
        ),
        migrations.AddField(
            model_name='contract',
            name='awarded_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='awarded_contracts', to='providers.provider'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='allowed_request_configs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='commercial_weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='functional_weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='kind',
            field=models.CharField(choices=[('Service', 'Service'), ('License', 'License'), ('Hardware', 'Hardware')], default='Service', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('In Negotiation', 'In Negotiation'), ('Awarded', 'Awarded'), ('Active', 'Active'), ('Expired', 'Expired')], default='Draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ContractAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_system', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, default='')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='contracts.contract')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_awards', to='providers.provider')),
            ],
        ),
    ]
