# Generated by Django 6.0 on 2026-01-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_remove_contract_awarded_provider_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractoffer',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
