# Generated by Django 6.0 on 2026-01-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contractoffer_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='accepted_request_types',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='allowed_domains',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='allowed_roles',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='experience_levels',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='offer_cycles_and_deadlines',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='offer_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='pricing_limits',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='version_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
