# Generated by Django 6.0 on 2026-01-19 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contract_config_and_offer_json_payloads'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='offer_deadline',
            new_name='offer_deadline_at',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='end_date',
            new_name='publishing_date',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='allowed_request_configs',
            new_name='stakeholders',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='accepted_request_types',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='allowed_domains',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='allowed_roles',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='awarded_provider',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='commercial_weight',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='experience_levels',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='functional_weight',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='offer_cycles_and_deadlines',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='pricing_limits',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='version_history',
        ),
        migrations.RemoveField(
            model_name='contractoffer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contractoffer',
            name='proposed_daily_rate',
        ),
        migrations.RemoveField(
            model_name='contractoffer',
            name='proposed_terms',
        ),
        migrations.AddField(
            model_name='contract',
            name='versions_and_documents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='weighting',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractoffer',
            name='created_by_user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='kind',
            field=models.CharField(choices=[('SERVICE', 'SERVICE'), ('LICENSE', 'LICENSE'), ('HARDWARE', 'HARDWARE')], default='SERVICE', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLISHED', 'PUBLISHED'), ('IN_NEGOTIATION', 'IN_NEGOTIATION'), ('ACTIVE', 'ACTIVE'), ('EXPIRED', 'EXPIRED')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='contractoffer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('SUBMITTED', 'SUBMITTED'), ('COUNTERED', 'COUNTERED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('WITHDRAWN', 'WITHDRAWN')], default='SUBMITTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='contractoffer',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ContractProviderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_NEGOTIATION', 'IN_NEGOTIATION'), ('ACTIVE', 'ACTIVE'), ('EXPIRED', 'EXPIRED')], default='IN_NEGOTIATION', max_length=30)),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_statuses', to='contracts.contract')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_statuses', to='providers.provider')),
            ],
            options={
                'unique_together': {('contract', 'provider')},
            },
        ),
        migrations.DeleteModel(
            name='ContractAward',
        ),
    ]
