# Generated by Django 6.0 on 2025-12-23 11:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(blank=True, max_length=255, null=True)),
                ("tax_id", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Specialist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "material_number",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "performance_grade",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "avg_daily_rate_eur",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialists",
                        to="providers.provider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpecialistRoleCapability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("JUNIOR", "Junior"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("SENIOR", "Senior"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "technology_level",
                    models.CharField(
                        choices=[
                            ("COMMON", "Common"),
                            ("UNCOMMON", "Uncommon"),
                            ("RARE", "Rare"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="specialist_caps",
                        to="accounts.roledefinition",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_capabilities",
                        to="providers.specialist",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="specialist",
            index=models.Index(
                fields=["provider"], name="providers_s_provide_41458d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="specialist",
            constraint=models.UniqueConstraint(
                fields=("provider", "material_number"),
                name="uniq_specialist_material_per_provider",
            ),
        ),
        migrations.AddConstraint(
            model_name="specialistrolecapability",
            constraint=models.UniqueConstraint(
                fields=(
                    "specialist",
                    "role_definition",
                    "experience_level",
                    "technology_level",
                ),
                name="uniq_specialist_role_level",
            ),
        ),
    ]
