# Generated by Django 6.0 on 2025-12-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="tax_id",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
