# Generated by Django 6.0 on 2026-01-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Single', 'Single'), ('Multi', 'Multi'), ('Team', 'Team'), ('Work Contract', 'Work Contract')], max_length=30)),
                ('linked_contract_id', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=100)),
                ('technology', models.CharField(blank=True, default='', max_length=255)),
                ('experience_level', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_man_days', models.PositiveIntegerField(default=0)),
                ('onsite_days', models.PositiveIntegerField(default=0)),
                ('performance_location', models.CharField(choices=[('Onshore', 'Onshore'), ('Nearshore', 'Nearshore'), ('Offshore', 'Offshore')], max_length=20)),
                ('required_languages', models.JSONField(blank=True, default=list)),
                ('must_have_criteria', models.JSONField(blank=True, default=list)),
                ('nice_to_have_criteria', models.JSONField(blank=True, default=list)),
                ('task_description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('Closed', 'Closed')], default='Draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
