# Generated by Django 6.0 on 2025-12-23 12:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_roleratepolicy"),
        ("providers", "0002_alter_provider_tax_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=20)),
                ("publishing_date", models.DateField(blank=True, null=True)),
                ("offer_deadline_at", models.DateTimeField(blank=True, null=True)),
                ("scope_of_work", models.TextField(blank=True, null=True)),
                ("terms_and_conditions", models.TextField(blank=True, null=True)),
                ("negotiation_history", models.JSONField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("functional_weight_pct", models.IntegerField(blank=True, null=True)),
                ("commercial_weight_pct", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceOffer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "daily_rate_eur",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "travel_cost_per_onsite_day_eur",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_cost_eur",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("contractual_relationship", models.CharField(max_length=30)),
                (
                    "subcontractor_company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status", models.CharField(max_length=20)),
                (
                    "match_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offers",
                        to="providers.provider",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offers",
                        to="providers.specialist",
                    ),
                ),
                (
                    "submitted_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_offers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceOfferMatchDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("details", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service_offer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_detail",
                        to="procurement.serviceoffer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("request_type", models.CharField(max_length=30)),
                (
                    "requested_by_external_id",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("status", models.CharField(max_length=20)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "domain_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("technology", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "experience_level",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("sum_man_days", models.IntegerField(blank=True, null=True)),
                ("onsite_days", models.IntegerField(blank=True, null=True)),
                (
                    "performance_location",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("task_description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_requests",
                        to="procurement.contract",
                    ),
                ),
                (
                    "role_definition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.roledefinition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("man_days", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_offer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accepted_into_order",
                        to="procurement.serviceoffer",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="providers.provider",
                    ),
                ),
                (
                    "role_definition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.roledefinition",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_orders",
                        to="providers.specialist",
                    ),
                ),
                (
                    "supplier_representative_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_orders_as_rep",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="procurement.servicerequest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="serviceoffer",
            name="service_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="procurement.servicerequest",
            ),
        ),
        migrations.CreateModel(
            name="ServiceRequestLanguage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("language", models.CharField(max_length=80)),
                ("skill_level", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="procurement.servicerequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceRequestRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.CharField(max_length=20)),
                ("skill_name", models.CharField(max_length=255)),
                ("weight_pct", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="procurement.servicerequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=120)),
                (
                    "entity_type",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("entity_id", models.UUIDField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="providers.provider",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider"], name="procurement_provide_4fc6aa_idx"
                    ),
                    models.Index(
                        fields=["actor_user"], name="procurement_actor_u_a203a8_idx"
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="procurement_entity__fe4597_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContractDomain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("domain_name", models.CharField(max_length=255)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="procurement.contract",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contract", "domain_name"), name="uniq_contract_domain"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContractRequestTypeRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_type", models.CharField(max_length=30)),
                ("offer_deadline_days", models.IntegerField()),
                ("cycles", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_type_rules",
                        to="procurement.contract",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contract", "request_type"),
                        name="uniq_contract_request_type_rule",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContractRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="procurement.contract",
                    ),
                ),
                (
                    "role_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.roledefinition",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contract", "role_definition"),
                        name="uniq_contract_role",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContractVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_no", models.IntegerField()),
                ("status", models.CharField(max_length=20)),
                ("document_url", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="procurement.contract",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contract", "version_no"),
                        name="uniq_contract_version_no",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceOrderChangeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("change_type", models.CharField(max_length=20)),
                ("initiated_by_type", models.CharField(max_length=20)),
                (
                    "initiated_by_external_id",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("status", models.CharField(max_length=20)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "initiated_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiated_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="procurement.serviceorder",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["service_order"], name="procurement_service_71328d_idx"
                    ),
                    models.Index(
                        fields=["change_type"], name="procurement_change__1a982f_idx"
                    ),
                    models.Index(
                        fields=["status"], name="procurement_status_f6a922_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["contract"], name="procurement_contrac_8513cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(fields=["status"], name="procurement_status_555da2_idx"),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["domain_name"], name="procurement_domain__3b8437_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["role_definition"], name="procurement_role_de_9cd914_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceorder",
            index=models.Index(
                fields=["service_request"], name="procurement_service_b5269c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceorder",
            index=models.Index(
                fields=["provider"], name="procurement_provide_5543c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceorder",
            index=models.Index(
                fields=["supplier_representative_user"],
                name="procurement_supplie_9e8b59_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="serviceorder",
            index=models.Index(
                fields=["specialist"], name="procurement_special_f1823f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceorder",
            index=models.Index(fields=["status"], name="procurement_status_224a0f_idx"),
        ),
        migrations.AddIndex(
            model_name="serviceoffer",
            index=models.Index(
                fields=["service_request"], name="procurement_service_3dce6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceoffer",
            index=models.Index(
                fields=["provider"], name="procurement_provide_b71099_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceoffer",
            index=models.Index(
                fields=["submitted_by_user"], name="procurement_submitt_28a8ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceoffer",
            index=models.Index(
                fields=["specialist"], name="procurement_special_2e597a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceoffer",
            index=models.Index(
                fields=["service_request", "provider"],
                name="procurement_service_5849b7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequestlanguage",
            constraint=models.UniqueConstraint(
                fields=("service_request", "language"), name="uniq_request_language"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequestrequirement",
            index=models.Index(
                fields=["service_request"], name="procurement_service_8b66f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequestrequirement",
            index=models.Index(
                fields=["service_request", "type"],
                name="procurement_service_2a8c14_idx",
            ),
        ),
    ]
