# Generated by Django 6.0 on 2026-01-05 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='experience_level',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='linked_contract_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='performance_location',
            field=models.CharField(blank=True, default='Onshore', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='role',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='type',
            field=models.CharField(choices=[('Single', 'Single'), ('Multi', 'Multi'), ('Team', 'Team'), ('Work Contract', 'Work Contract')], default='Single', max_length=30),
        ),
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('travel_cost_per_onsite_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contractual_relationship', models.CharField(choices=[('Employee', 'Employee'), ('Freelancer', 'Freelancer'), ('Subcontractor', 'Subcontractor')], default='Employee', max_length=30)),
                ('subcontractor_company', models.CharField(blank=True, max_length=255, null=True)),
                ('must_have_match_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('nice_to_have_match_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Withdrawn', 'Withdrawn'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Draft', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_offers_created', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_offers', to='providers.provider')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='procurement.servicerequest')),
                ('specialist', models.ForeignKey(limit_choices_to={'role': 'Specialist'}, on_delete=django.db.models.deletion.CASCADE, related_name='service_offers_as_specialist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
