# Generated by Django 6.0 on 2026-01-07 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_remove_servicerequest_updated_at_and_more'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='Onshore', max_length=50)),
                ('man_days', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='providers.provider')),
                ('service_offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_order', to='procurement.serviceoffer')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='procurement.servicerequest')),
                ('specialist', models.ForeignKey(limit_choices_to={'role': 'Specialist'}, on_delete=django.db.models.deletion.PROTECT, related_name='service_orders_as_specialist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
