# Generated by Django 6.0 on 2026-01-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_serviceorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='change_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=12),
        ),
    ]
