# Generated by Django 6.0 on 2026-01-08 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_serviceorder_change_history_serviceorder_status'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='change_history',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=10),
        ),
        migrations.CreateModel(
            name='ServiceOrderChangeRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Extension', 'Extension'), ('Substitution', 'Substitution')], max_length=20)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Requested', max_length=20)),
                ('created_by_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('provider_response_note', models.TextField(blank=True, default='')),
                ('new_end_date', models.DateField(blank=True, null=True)),
                ('additional_man_days', models.PositiveIntegerField(blank=True, null=True)),
                ('new_total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_order_change_requests_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_order_change_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('new_specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_order_change_requests_new_specialist', to=settings.AUTH_USER_MODEL)),
                ('old_specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_order_change_requests_old_specialist', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_order_change_requests', to='providers.provider')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='procurement.serviceorder')),
            ],
        ),
    ]
