# Generated by Django 6.0 on 2026-01-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_remove_serviceorder_change_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='cycles',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='offer_deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='linked_contract_id',
            field=models.CharField(default='CR001', max_length=20),
            preserve_default=False,
        ),
    ]
