# Generated by Django 6.0 on 2026-01-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_sr_offer_payloads_multi_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='offer_deadline_at',
            new_name='bidding_end_at',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='experience_level',
            new_name='contract_id',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='technology',
            new_name='contract_supplier',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='payload',
            new_name='external_payload',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='technology_level',
            new_name='project_id',
        ),
        migrations.RemoveField(
            model_name='serviceoffer',
            name='contractual_relationship',
        ),
        migrations.RemoveField(
            model_name='serviceoffer',
            name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='serviceoffer',
            name='must_have_match_percentage',
        ),
        migrations.RemoveField(
            model_name='serviceoffer',
            name='nice_to_have_match_percentage',
        ),
        migrations.RemoveField(
            model_name='serviceoffer',
            name='specialist',
        ),
        migrations.RemoveField(
            model_name='serviceoffer',
            name='subcontractor_company',
        ),
        migrations.RemoveField(
            model_name='serviceoffer',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='serviceoffer',
            name='travel_cost_per_onsite_day',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='specialist',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='cycles',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='linked_contract_id',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='onsite_days',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='positions',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='role',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='total_man_days',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='specialist_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='bidding_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='bidding_cycle_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='bidding_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='further_information',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='max_accepted_offers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='max_offers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='request_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='requested_by_role',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='requested_by_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('SUBMITTED', 'SUBMITTED'), ('WITHDRAWN', 'WITHDRAWN'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='location',
            field=models.CharField(blank=True, default='Onsite', max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='man_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('COMPLETED', 'COMPLETED')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='performance_location',
            field=models.CharField(blank=True, default='Onsite', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(blank=True, default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='type',
            field=models.CharField(blank=True, default='SINGLE', max_length=30),
        ),
        migrations.DeleteModel(
            name='ServiceOrderChangeRequest',
        ),
    ]
