# Generated by Django 6.0 on 2026-01-20 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_rename_offer_deadline_at_servicerequest_bidding_end_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceoffer',
            old_name='deltas',
            new_name='group3_last_response',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='specialist_id',
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='group3_last_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('SUBMITTED', 'SUBMITTED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='service_offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_order', to='procurement.serviceoffer'),
        ),
        migrations.CreateModel(
            name='ServiceOrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('travelling_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('specialist_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('match_must_have_criteria', models.BooleanField(default=True)),
                ('match_nice_to_have_criteria', models.BooleanField(default=True)),
                ('match_language_skills', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='procurement.serviceorder')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_order_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('order', 'specialist')},
            },
        ),
    ]
