# Generated by Django 6.0 on 2026-01-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_serviceorderchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderchangerequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorderchangerequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorderchangerequest',
            name='substitution_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
