# Generated by Django 6.0 on 2026-01-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_serviceorderchangerequest_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderassignment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorderassignment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
