# Generated by Django 6.0 on 2025-12-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='counter_proposal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
